src/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from .views import main, login_user, logout, registr_user, register_confirm, profile, edit, \
    account, api, APIUser, APIUserEdit,\
    APIProfile, APIProfileEdit, APIAccount, validate_username


urlpatterns = [
    path('', main, name='main'),
    path('login/', login_user, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', registr_user, name='register'),
    url(r'^register/confirm/(?P<key>[0-9a-f]{32})/$', register_confirm, name='register_confirm'),
    path('profile/', profile, name='profile'),
    path('edit/', edit, name='edit'),
    path('account_type/', account, name='account'),
    path('api/', api, name='api'),
    path('api/user/get/', APIUser.as_view()),
    path('api/user/edit/', APIUserEdit.as_view()),
    path('api/profile/get/', APIProfile.as_view()),
    path('api/profile/edit/', APIProfileEdit.as_view()),
    path('api/account/', APIAccount.as_view()),
    path('validate_username', validate_username, name='validate_username'),
    ]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from .sitemaps import HomePageSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


sitemaps = {
    'home': HomePageSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('records.urls')),
    path('chats/', include('dialogs.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', include('social_django.urls', namespace='social')),
]

handler404 = 'views.my_custom_page_not_found_view'
handler500 = 'views.my_custom_error_view'
handler403 = 'views.my_custom_permission_denied_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import uuid
from django.dispatch import receiver
from django.utils.timezone import now
from django.db.models.signals import pre_delete, post_save


class Profile(models.Model):
    """
    Information about an author.
    """
    objects = None
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    account_type = models.CharField(max_length=15, default='Standard')
    birthday = models.DateField(blank=True, null=True,
                                help_text="Birthday in YYYY-MM-DD format [used for displaying age].")
    location = models.CharField(max_length=40, blank=True, help_text="Geographic location.")
    website = models.URLField(blank=True, help_text="A personal blog or website.")
    bio = models.TextField(max_length=500, blank=True, help_text="A brief biography.")
    image = models.ImageField(upload_to='avatar/', blank=True, null=True)

    def __str__(self):
        return self.user.get_full_name() or self.user.get_username()

    def age(self):
        """
        Calculate the age of the user.
        """
        if not self.birthday:
            return None
        n, b = now().date(), self.birthday
        return n.year - b.year - (0 if n.month > b.month or n.month == b.month and n.day >= b.day else 1)

    class Meta:
        ordering = ('-user__last_login',)


@receiver(pre_delete, sender=Profile)
def image_profile_delete(sender, instance, **kwargs):
    instance.image.delete(False)


@receiver(post_save, sender=User)
def create_profile(instance, created, **kwargs):
    """
    Create a profile whenever a user is created.
    """
    if created:
        Profile.objects.create(user=instance)


class Account(models.Model):
    objects = None
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    account_type = models.CharField(max_length=15, default='Standard')
    key = models.CharField(max_length=20, blank=True, null=True)


@receiver(models.signals.post_save, sender=Profile)
def create_account(instance, created, **kwargs):
    """
    Create an account whenever a profile is created.
    """
    if created:
        Account.objects.create(profile=instance)


class ConfirmationKey(models.Model):
    """
    Unique token for confirming a user account or resetting a password.
    """
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    key = models.CharField(max_length=32, default=uuid)


class PageView(models.Model):
    objects = None
    url = models.CharField(max_length=70, blank=True, null=True, unique=True)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.url} - {self.views}'

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Account


class RegistrForm(UserCreationForm):
    """
    Form for new user registrations.
    """
    email = forms.EmailField(required=True, max_length=250, help_text="Used for account verification "
                                                                      "and password resets.")


class AccountKeyForm(forms.ModelForm):
    """
    Form for entering the key and switching to a premium account.
    """
    class Meta:
        model = Account
        fields = ('key',)


class ProfileForm(forms.ModelForm):
    """
    Form for editing a user's profile.
    """
    first_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="First name [optional].",
    )
    last_name = forms.CharField(
        max_length=30,
        required=False,
        help_text="Last name [optional].",
    )
    email = forms.EmailField(help_text="Used for account verification and password resets.")

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'email', 'birthday', 'location', 'website', 'bio', 'image')

src/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegistrForm, ProfileForm, AccountKeyForm
from django.template import loader
from django.core.mail import send_mail
from django.urls import reverse
from .models import ConfirmationKey, Profile, Account, PageView
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import login, logout as logout_user
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .serializers import UserSerializer, UserEditSerializer, ProfileSerializer, ProfileEditSerializer, AccountSerializer
from rest_framework import generics
from django.contrib.auth.models import User
from django.db.models import F
from PIL import Image
import io
from django.core.files.base import ContentFile
from django.http import JsonResponse


MAX_SIZE = 300


def csrf_failure(request, reason=""):
    ctx = {'message': ' Error 403. This user is already logged in!'}
    return render(request, '403.html', ctx)


def entrance_url(url):
    entrance = PageView.objects.filter(url=url)
    entrance.update(views=F('views') + 1)


def main(request):
    if request.method == 'GET':
        PageView.objects.get_or_create(url='main')
        entrance_url('main')
        profile_image = Profile.objects.filter(user_id=request.user.id).first()
        return render(request, 'main.html', {'profile': profile_image})


def login_user(request):
    """
        Log a user in.
    """
    if request.method == 'GET':
        logout_user(request)
        context = {'form': AuthenticationForm()}
        return render(request, 'login.html', context)
    elif request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if not form.is_valid():
            messages.error(request, 'Your input is invalid!')
            return redirect('login')
        messages.success(request, 'Welcome!')
        login(request, form.get_user())
        return redirect('main')


@login_required
def logout(request):
    """
    Log a user out.
    """
    logout_user(request)
    messages.info(request, "You have successfully been logged out.")
    return redirect('main')


def registr_user(request):
    """
        Present a registration form for new users.
    """
    if request.method == 'GET':
        logout_user(request)
        context = {'form': RegistrForm(), 'description': "Please fill in the form below to create your account."}
        return render(request, 'register.html', context)
    elif request.method == 'POST':
        form = RegistrForm(data=request.POST)
        if not form.is_valid():
            messages.error(request, 'Your input is invalid!')
            return redirect('register')
        user = form.save(commit=False)
        user.email = form.cleaned_data['email']
        user.is_active = False
        user.save()
        key = ConfirmationKey(user=user)
        key.save()
        template = loader.render_to_string('email/register.txt', {
            'user': user,
            'url': request.build_absolute_uri(reverse('register_confirm', kwargs={'key': key.key}))
        })
        send_mail('Diary Registration', template, 'Diary <antonkomp1@gmail.com>', [user.email])
        messages.info(request,
                      "Please check the email address you provided for instructions on activating your account.")
        return redirect('main')


def validate_username(request):
    """Check username availability"""
    username = request.GET.get('username', None)
    response = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(response)


def register_confirm(request, key):
    """
    Confirms a user account.
    :param request:
    :param key: confirmation key to confirm registration
    """
    key = get_object_or_404(ConfirmationKey, key=key)
    key.user.is_active = True
    key.user.save()
    key.delete()
    messages.info(request, "Thank you! Your account has been activated.")
    return redirect('login')


@login_required
def profile(request):
    """
    Display a user's profile.
    """
    PageView.objects.get_or_create(url='profile')
    entrance_url('profile')
    prof = Profile.objects.filter(user_id=request.user.id).first()
    return render(request, 'profile.html', {'profile': prof})


def upload_avatar(prof, prof_old):
    if prof.image.width > MAX_SIZE or prof.image.height > MAX_SIZE:
        with Image.open(prof.image) as img:
            img.thumbnail((MAX_SIZE, MAX_SIZE), Image.ANTIALIAS)
            thumb_io = io.BytesIO()
            img.save(thumb_io, img.format, quality=90)
            prof.image.save(prof.image.name, ContentFile(thumb_io.getvalue()), save=False)
    prof_old.image = prof.image


@login_required
def edit(request):
    prof = get_object_or_404(Profile, user=request.user.id)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=prof)
        if form.is_valid():
            prof_old = Profile.objects.get(user_id=request.user.id)
            prof.user.first_name = form.cleaned_data['first_name']
            prof.user.last_name = form.cleaned_data['last_name']
            prof.user.email = form.cleaned_data['email']
            if prof.image.name != prof_old.image.name:
                if prof.image.name == '' and prof_old.image.name != '':
                    prof_old.image.delete()
                elif prof.image.name != '' and prof_old.image.name != '':
                    prof_old.image.delete()
                    upload_avatar(prof, prof_old)
                else:
                    upload_avatar(prof, prof_old)
            prof.user.save()
            form.save()
            messages.success(request, 'Profile edited.')
            return redirect('profile')
        else:
            messages.error(request, 'Your input is invalid!')
            return redirect('edit')
    else:
        form = ProfileForm(
            instance=prof,
            initial={
                'first_name': prof.user.first_name,
                'last_name': prof.user.last_name,
                'email': prof.user.email,
            })
        profile_image = Profile.objects.filter(user_id=request.user.id).first()
        return render(request, "edit.html", {'form': form, 'profile': profile_image})


@login_required
def account(request):
    if request.method == 'GET':
        PageView.objects.get_or_create(url='account')
        entrance_url('account')
        acc = Account.objects.filter(profile_id=request.user.id).first()
        form = AccountKeyForm()
        profile_image = Profile.objects.filter(user_id=request.user.id).first()
        context = {'account': acc, 'form': form, 'profile': profile_image}
        return render(request, 'account.html', context)
    if request.method == 'POST':
        form = AccountKeyForm(request.POST, request.FILES)
        if not form.is_valid():
            return HttpResponse('Your input is invalid', status=400)
        data = form.cleaned_data
        acc = Account.objects.get(profile_id=request.user.id)
        prof = Profile.objects.get(user_id=request.user.id)
        if data['key'] == 'kovrizhka':
            acc.key = data['key']
            acc.account_type = 'Premium'
            prof.account_type = 'Premium'
            messages.success(request, 'Congratulations, you have switched to a Premium account!')
        elif data['key'] == 'backtoschool':
            acc.key = data['key']
            acc.account_type = 'Standard'
            prof.account_type = 'Standard'
            messages.success(request, 'You have switched to a Standard account!')
        else:
            messages.warning(request, 'The wrong key was entered!')
        acc.save()
        prof.save()
        return redirect('account')


@login_required
def api(request):
    PageView.objects.get_or_create(url='api')
    entrance_url('api')
    profile_image = Profile.objects.filter(user_id=request.user.id).first()
    return render(request, 'API.html', {'profile': profile_image})


class APIUser(generics.RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    def get_object(self):
        try:
            queryset = self.filter_queryset(self.get_queryset())
            obj = queryset.get(pk=self.request.user.id)
            self.check_object_permissions(self.request, obj)
            return obj
        except User.DoesNotExist:
            pass


class APIUserEdit(generics.RetrieveUpdateAPIView):
    queryset = User.objects.all()
    serializer_class = UserEditSerializer

    def get_object(self):
        try:
            queryset = self.filter_queryset(self.get_queryset())
            obj = queryset.get(pk=self.request.user.id)
            self.check_object_permissions(self.request, obj)
            return obj
        except User.DoesNotExist:
            pass


class APIProfile(generics.RetrieveAPIView):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer

    def get_object(self):
        try:
            queryset = self.filter_queryset(self.get_queryset())
            obj = queryset.get(pk=self.request.user.id)
            self.check_object_permissions(self.request, obj)
            return obj
        except Profile.DoesNotExist:
            pass


class APIProfileEdit(generics.RetrieveUpdateAPIView):
    queryset = Profile.objects.all()
    serializer_class = ProfileEditSerializer

    def get_object(self):
        try:
            queryset = self.filter_queryset(self.get_queryset())
            obj = queryset.get(pk=self.request.user.id)
            self.check_object_permissions(self.request, obj)
            return obj
        except Profile.DoesNotExist:
            pass


class APIAccount(generics.RetrieveAPIView):
    queryset = Account.objects.all()
    serializer_class = AccountSerializer

    def get_object(self):
        try:

src/accounts/templates/API.html
{% extends "base.html" %}
{% block title %} API {% endblock %}

{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'css/api/api.css' %}" />
{% endblock %}

{% block content %}
<h1 align="center" style="color:#ff0099">API</h1>
<p>API - application programming interface.</p>
<h2>Content</h2>
<ol class="without_std_numb">
    <li class="without_std_numb"> <a href='#authorization'>Authorization</a>
        <ol class="without_std_numb">
            <li class="without_std_numb"><a href='#get_data_auth'>Get data</a>
                <ol class="without_std_numb">
                    <li class="without_std_numb"><a href='#get_data_auth_request'>Request format</a></li>
                    <li class="without_std_numb"><a href='#get_data_auth_parameters'>Response</a></li>
                </ol>
            </li>
            <li class="without_std_numb"><a href='#edit_auth'>Edit</a>
                <ol class="without_std_numb">
                    <li class="without_std_numb"><a href='#edit_auth_request'>Request format</a></li>
                    <li class="without_std_numb"><a href='#edit_auth_parameters'>Response</a></li>
                </ol>
            </li>
        </ol>
    </li>
    <li class="without_std_numb"> <a href='#profile'>Working with user profile</a>
        <ol class="without_std_numb">
            <li class="without_std_numb"><a href='#profile_get_data'>Get data</a>
                <ol class="without_std_numb">
                    <li class="without_std_numb"><a href='#profile_get_data_request'>Request format</a></li>
                    <li class="without_std_numb"><a href='#profile_get_data_edit'>Response</a></li>
                </ol>
            </li>
            <li class="without_std_numb"><a href='#profile_edit'>Edit</a>
                <ol class="without_std_numb">
                    <li class="without_std_numb"><a href='#profile_edit_request'>Request format</a></li>
                    <li class="without_std_numb"><a href='#profile_edit_parameters'>Response</a></li>
                </ol>
            </li>
        </ol>
    </li>
    <li class="without_std_numb"><a href='#account'>Working with account</a>
        <ol class="without_std_numb">
            <li class="without_std_numb"><a href='#account_get_data'>Get data</a>
                <ol class="without_std_numb">
                    <li class="without_std_numb"><a href='#account_get_data_request'>Request format</a></li>
                    <li class="without_std_numb"><a href='#account_get_data_parameters'>Response</a></li>
                </ol>
            </li>
        </ol>
    <li class="without_std_numb"><a href='#entries'>Working with diary entries</a></li>
        <ol class="without_std_numb">
            <li class="without_std_numb"><a href='#entries_get_all_entries'>Get all entries</a>
                <ol class="without_std_numb">
                    <li class="without_std_numb"><a href='#entries_get_all_entries_request'>Request format</a></li>
                    <li class="without_std_numb"><a href='#entries_get_all_entries_parameters'>Response</a></li>
                </ol>
            </li>
            <li class="without_std_numb"><a href='#entries_create_entry'>Create entry</a>
                <ol class="without_std_numb">
                    <li class="without_std_numb"><a href='#entries_create_entry_request'>Request format</a></li>
                    <li class="without_std_numb"><a href='#entries_create_entry_parameters'>Response</a></li>
                </ol>
            </li>
            <li class="without_std_numb"><a href='#entries_edit_entry'>Edit entry</a>
                <ol class="without_std_numb">
                    <li class="without_std_numb"><a href='#entries_edit_entry_request'>Request format</a></li>
                    <li class="without_std_numb"><a href='#entries_edit_entry_parameters'>Response</a></li>
                </ol>
            </li>
            <li class="without_std_numb"><a href='#entries_delete_entry'>Delete entry</a>
                <ol class="without_std_numb">
                    <li class="without_std_numb"><a href='#entries_delete_entry_request'>Request format</a></li>
                    <li class="without_std_numb"><a href='#entries_delete_entry_parameters'>Response</a></li>
                </ol>
            </li>
        </ol>
    </li>
</ol>
<br>
<h2 id='authorization' >Authorization</h2>
<hr>
<h3 id='get_data_auth'>Get data</h3>
<h4 id='get_data_auth_request'>Request format</h4>
<table border="1" cellpadding="5">
    <tr>
        <th>/api/user/get/</th>
    </tr>
</table>
<h4 id='get_data_auth_parameters'>Response</h4>
<p> 1. 'id' - идентификатор пользователя,</p>
<p> 2. 'last_login - дата и время последней авторизации пользователя,</p>
<p> 3. 'username' - пользовательское имя,</p>
<p> 4. 'first_name' - имя пользователя,</p>
<p> 5. 'last_name' - фамилия пользователя,</p>
<p> 6. 'is_active - доступ пользователя,</p>
<p> 7. 'date_joined' - дата и время регистрации пользователя.</p>

<h3 id='edit_auth'>Edit</h3>
<h4 id='edit_auth_request'>Request format</h4>
<table border="1" cellpadding="5">
    <tr>
        <th>/api/user/edit/</th>
    </tr>
</table>
<h4 id='edit_auth_parameters'>Response</h4>
<p> 1. 'username' - пользовательское имя,</p>
<p> 2. 'first_name' - имя пользователя,</p>
<p> 3. 'last_name' - фамилия пользователя,</p>
<p> 4. 'email' - почтовый ящик пользователя.</p>
<br>
<h2 id='profile' >Working with user profile</h2>
<hr>
<h3 id='profile_get_data'>Get data</h3>
<h4 id='profile_get_data_request'>Request format</h4>
<table border="1" cellpadding="5">
    <tr>
        <th>/api/profile/get/</th>
    </tr>
</table>
<h4 id='profile_get_data_edit'>Response</h4>
<p> 1. 'user' - номер пользователя в системе,</p>
<p> 2. 'account_type' - тип аккаунта пользователя,</p>
<p> 3. 'birthday' - день рождения,</p>
<p> 4. 'location' - местоположение,</p>
<p> 5. 'website' - вебсайт пользователя,</p>
<p> 6. 'bio' - краткая биография пользователя.</p>
<h3 id='profile_edit'>Edit</h3>
<h4 id='profile_edit_request'>Request format</h4>
<table border="1" cellpadding="5">
    <tr>
        <th>/api/profile/edit/</th>
    </tr>
</table>
<h4 id='profile_edit_parameters'>Response</h4>
<p> 1. 'birthday' - день рождения,</p>
<p> 2. 'location' - местоположение,</p>
<p> 3. 'website' - вебсайт пользователя,</p>
<p> 4. 'bio' - краткая биография пользователя.</p>
<br>
<h2 id='account' >Working with account</h2>
<hr>
<h3 id='account_get_data'>Get data</h3>
<h4 id='account_get_data_request'>Request format</h4>
<table border="1" cellpadding="5">
    <tr>
        <th>/api/account/</th>
    </tr>
</table>
<h4 id='account_get_data_parameters'>Response</h4>
<p> 1. 'id' - идентификатор пользователя,</p>
<p> 2. 'account_type' - тип аккаунта пользователя,</p>
<p> 3. 'key' - ключ для изменения типа аккаунта.</p>
<br>
<h2 id='entries' >Working with diary entries</h2>
<hr>
<h3 id='entries_get_all_entries'>Get all entries</h3>
<h4 id='entries_get_all_entries_request'>Request format</h4>
<table border="1" cellpadding="5">
    <tr>
        <th>/api/entries/</th>
    </tr>
</table>
<h4 id='entries_get_all_entries_parameters'>Response</h4>
<p> 1. 'id' - идентификатор записи,</p>
<p> 2. 'date' - дата и время создания записи,</p>
<p> 3. 'header' - заголовок записи,</p>
<p> 4. 'text' - текст записи,</p>
<p> 5. 'image' - прикрепленное изображение к записи.</p>

<h3 id='entries_create_entry'>Create entry</h3>
<h4 id='entries_create_entry_request'>Request format</h4>
<table border="1" cellpadding="5">
    <tr>
        <th>/api/entry/create/</th>
    </tr>
</table>
<h4 id='entries_create_entry_parameters'>Response</h4>
<p> 1. 'header' - заголовок записи,</p>
<p> 2. 'text' - текст записи,</p>
<p> 3. 'image' - прикрепленное изображение к записи.</p>

<h3 id='entries_edit_entry'>Edit entry</h3>
<h4 id='entries_edit_entry_request'>Request format</h4>
<table border="1" cellpadding="5">
    <tr>
        <th>/api/entry/update/[pk]/</th>
    </tr>
</table>
<p>
    Parameter [pk] - number of the entry you want to update.
</p>
<h4 id='entries_edit_entry_parameters'>Response</h4>
<p> 1. 'header' - заголовок записи,</p>
<p> 2. 'text' - текст записи,</p>
<p> 3. 'image' - прикрепленное изображение к записи,</p>
<p> 4. 'delete_image' - возможность удалить изображение.</p>

<h3 id='entries_delete_entry'>Delete entry</h3>
<h4 id='entries_delete_entry_request'>Request format</h4>
<table border="1" cellpadding="5">
    <tr>
        <th>/api/entry/delete/[pk]/</th>
    </tr>
</table>
<p>
    Parameter [pk] - number of the entry you want to delete.
</p>
<h4 id='entries_delete_entry_parameters'>Response</h4>
<p> 1. 'id' - идентификатор записи,</p>
<p> 2. 'date' - дата и время создания записи,</p>
<p> 3. 'header' - заголовок записи,</p>
<p> 4. 'text' - текст записи,</p>
<p> 5. 'image' - прикрепленное изображение к записи.</p>
<hr>
<a style="color:green;" href="{% url 'profile' %}"> Profile user </a><br><br>
{% endblock %}

src/accounts/templates/account.html
{% extends "base.html" %}
{% block title %} Account {% endblock %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'css/accounts/account.css' %}" />
{% endblock %}
{% block content %}
{% for message in messages %}
        <div class="alert {% if message.tags == 'error' %} alert-danger {% elif message.tags == 'warning' %} alert-warning
         {% else %} alert-info {% endif %}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
{% endfor %}
<h3>Account type details</h3>
<p>Type: {{ account.account_type }}</p>
{% if account.account_type == "Standard" %}
    <p>By subscribing for a <b>Premium</b> account, you will get access to some extra features.
        You will also be supporting future updates and improvements of this free service.
        Some new features will only be available to subscribers.</p>
    <ul>
      <li><b>Pictures</b> in entries and messages.</li>
      <li><b>No advertisements</b> while logged in.</li>
      <li>The ability to create <b>voice recordings</b>!</li>
      <li>Using the <b>API</b>.</li>
    </ul>
    <p>To upgrade to a <b>Premium</b> account you need to enter a key:</p>
    <form action="{% url 'account' %}" method="POST">
            {% csrf_token %}
            {{ form.key }}
            <input class="send" type="submit" value="Send"/>
    </form><br>
{% elif account.account_type == "Premium" %}
    <p>Thank you for switching to a premium account and becoming our subscriber.<br>
        Now you can upload <b>images</b> to your diary, record <b>voice messages</b> and <b>no ads</b>!</p>
    <form action={% url 'account' %} method="POST">
            {% csrf_token %}
            {{ form.key }}
            <input class="send" type="submit" value="Send"/>
    </form><br>
{% endif %}
    <hr>
    <a class="profile" href="{% url 'profile' %}"> Profile user </a><br>

{% endblock %}

src/accounts/templates/edit.html
{% extends "base.html" %}
{% block title %} Edit profile {% endblock %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'css/accounts/edit.css' %}" />
{% endblock %}
{% block content %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'error' %} alert-danger {% else %} alert-info {% endif %}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor %}
    <h3>Edit profile</h3>
    <p>Use the form below to make changes to this user profile.</p>
    <form action={% url 'edit' %} enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="edit_save" type="submit" value="Save"/>
    </form><br>
    <hr>
    <a class="profile" href="{% url 'profile' %}"> Profile user </a><br><br><br>
    <script>
        $('#id_birthday').keyup(function () {
            var birthday_value = document.getElementById('id_birthday').value;
            if ((!/^(19[2-9][0-9]|20[0-1][0-9])[-](0[1-9]|1[0-2])[-](0[1-9]|[1-2][0-9]|3[0-1])$/.test(birthday_value))
            && (/^./.test(birthday_value))) {
                $('#id_birthday').removeClass('is-valid').addClass('is-invalid');
                $('#id_birthday').css({"border-color": "red", "background": "#FDF5F5"});
                $('.edit_save').attr("disabled", true);
                $('.edit_save').css({"background": "#9c9c9c"});
            }
            else {
                $('#id_birthday').removeClass('is-invalid').addClass('is-valid');
                $('#id_birthday').css({"border-color": "black", "background": "#eceff3"});
                $('.edit_save').removeAttr("disabled");
                $('.edit_save').css({"background": "#1a73e8"});
            }
        });
    </script>
{% endblock %}

src/accounts/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Log in {% endblock %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'css/accounts/login.css' %}" />
{% endblock %}
{% block content %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-info{% endif %}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor %}
    <h3>Log in</h3>
    <form action={% url "login" %} method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <input class="log_buttons" type="submit" value="Log in"/>
        <input class="log_buttons" type="reset" value="Clear"/>
    </form>
    <p>or</p>
    <a class="auth_google" href="{% url 'social:begin' 'google-oauth2' %}">
        Log in with Google
    </a><br>
    <a class="auth_facebook" href="{% url 'social:begin' 'facebook' %}">
        Log in with Facebook
    </a><br>
    <a class="auth_linkidin" href="{% url 'social:begin' 'linkedin-oauth2' %}">
        Log in with LinkidIn
    </a>

{% endblock %}