src/records/urls.py
from django.urls import path, re_path
from .views import (
    add_entry, all_entries, detail_entry, edit_entry, delete_entry, open_image, send_entry,
    APIEntries, APICreateEntry, APIUpdateEntry, APIDeleteEntry,
    delete_voice_record, my_public_diaries, create_new_diary, all_public_diaries
)


urlpatterns = [
    path('add_entry/', add_entry, name='add_entry'),
    path('my_public_diaries/', my_public_diaries, name='my_public_diaries'),
    path('create_new_diary/', create_new_diary, name='create_new_diary'),
    path('all_public_diaries/', all_public_diaries, name='all_public_diaries'),
    path('all_entries/', all_entries, name='all_entries'),
    path('details_entry/<int:entry_id>/', detail_entry, name='detail_entry'),
    path('edit_entry/<int:entry_id>/', edit_entry, name='edit_entry'),
    path('delete_entry/<int:entry_id>/', delete_entry, name='delete_entry'),
    path('open_image/<int:entry_id>/', open_image, name='open_image'),
    path('send_entry/<int:entry_id>/', send_entry, name='send_entry'),
    path('api/entries/', APIEntries.as_view()),
    path('api/entry/create/', APICreateEntry.as_view()),
    path('api/entry/update/<int:pk>/', APIUpdateEntry.as_view()),
    path('api/entry/delete/<int:pk>/', APIDeleteEntry.as_view()),
    re_path(r'^page/(\d+)/$', all_entries, name='all_entries'),
    path('delete_voice_record/<int:entry_id>/', delete_voice_record, name='delete_voice_record'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from .sitemaps import HomePageSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


sitemaps = {
    'home': HomePageSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('records.urls')),
    path('chats/', include('dialogs.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', include('social_django.urls', namespace='social')),
]

handler404 = 'views.my_custom_page_not_found_view'
handler500 = 'views.my_custom_error_view'
handler403 = 'views.my_custom_permission_denied_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

src/records/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
import os


class Diary(models.Model):
    objects = None
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=150, null=False)

    def __str__(self):
        return f'User: {self.user} - Diary: {self.name}'


class Entry(models.Model):
    DoesNotExist = None
    objects = None
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateTimeField(auto_now=True)
    check_edit = models.BooleanField(default=False)
    header = models.CharField(max_length=70, default='no_theme')
    text = models.TextField(max_length=9999, blank=True, null=True)
    image = models.ImageField(upload_to='image_entries/', blank=True, null=True)
    delete_image = models.BooleanField(default=False)
    voice_record = models.FileField(upload_to='voice_record/', blank=True, null=True)

    def __str__(self):
        return f'{self.header} ({self.user}) - {str(self.date)[:19]}   {"📷" if self.image else " "}' \
               f' {"🎵" if self.voice_record else " "}'

    class Meta:
        ordering = ('-date', '-user',)

    @property
    def image_filename(self):
        return os.path.basename(self.image.name)

    @property
    def voice_filename(self):
        return os.path.basename(self.voice_record.name)


@receiver(pre_delete, sender=Entry)
def image_entry_delete(sender, instance, **kwargs):
    instance.image.delete(False)


@receiver(pre_delete, sender=Entry)
def voice_record_entry_delete(sender, instance, **kwargs):
    instance.voice_record.delete(False)

src/records/forms.py
from .models import Entry, Diary
from django import forms


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ('header', 'text', 'image', 'delete_image',)


class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('name',)

src/records/views.py
from django.shortcuts import render, redirect
from .forms import EntryForm, DiaryForm
from .models import Entry, Diary
from accounts.models import PageView, Profile
from django.forms import model_to_dict
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.mail import EmailMessage
from django.views.decorators.http import require_http_methods
from django.http import HttpResponseRedirect
from django.template.loader import render_to_string
from .serializers import EntrySerializer, CreateEntrySerializer, UpdateEntrySerializer, DeleteEntrySerializer
from rest_framework import generics
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import F, Q
from PIL import Image, UnidentifiedImageError
import io
from django.core.files.base import ContentFile
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
import json


MAX_SIZE = 1024

SUCCESS_MESSAGE = 'New entry added!'
SUCCESS_VOICE_MESSAGE = 'New entry with voice record added!'


def entrance_url(url):
    entrance = PageView.objects.filter(url=url)
    entrance.update(views=F('views') + 1)


def resize_image(us):
    if us.image.width <= MAX_SIZE and us.image.height <= MAX_SIZE:
        return

    try:
        with Image.open(us.image) as img:
            img.thumbnail((MAX_SIZE, MAX_SIZE), Image.ANTIALIAS)
            thumb_io = io.BytesIO()
            img.save(thumb_io, format=img.format, quality=86)

            if img.size != us.image.size:
                us.image.save(us.image.name, ContentFile(thumb_io.getvalue()), save=False)
    except UnidentifiedImageError:
        pass


@login_required
def add_entry(request):
    """Add entry"""
    if request.method == 'POST':
        form = EntryForm(request.POST, request.FILES)
        if form.is_valid():
            us = form.save(commit=False)
            us.user = request.user
            if request.is_ajax():
                us.header = request.POST.get('header')
                us.text = request.POST.get('text')
                us.voice_record = request.FILES.get('audio_data')
                us.image = request.FILES.get('image')
                us.delete_image = json.loads(request.POST.get('delete_image').lower())
                messages.success(request, 'New entry with voice record added!')

            if us.image.name is not None and us.delete_image:
                us.image = ''
            elif us.image.name is not None and us.delete_image is False and us.header != '!original!':
                resize_image(us)

            us.save()
            if request.is_ajax():
                return JsonResponse({'success': True, })

            messages.success(request, 'New entry added!')
            return redirect('all_entries')

        return JsonResponse({'success': False, })
    else:
        form = EntryForm()
        profile_image = Profile.objects.filter(user_id=request.user.id).first()
        return render(request, 'add_entry.html', {'form': form, 'profile': profile_image})


def handle_ajax_request():
    return JsonResponse({'success': True})


@login_required
def create_new_diary(request):
    """Create new diary"""
    if request.method == 'POST':
        form = DiaryForm(request.POST)
        if form.is_valid():
            us = form.save(commit=False)
            us.user = request.user
            us.save()
            messages.success(request, 'New diary created!')
            return redirect('my_public_diaries')
    else:
        form = DiaryForm()
        profile_image = get_object_or_404(Profile, user_id=request.user.id)
        context = {'form': form, 'profile': profile_image}
        return render(request, 'create_new_diary.html', context)


@login_required
def all_public_diaries(request):
    context = {}
    return render(request, 'all_public_diaries.html', context)


@login_required
def my_public_diaries(request):
    if request.method == "GET":
        profile_image = get_object_or_404(Profile, user_id=request.user.id)
        diaries_user = Diary.objects.filter(user_id=request.user.id).select_related('user')

        context = {'profile': profile_image, 'diaries': diaries_user}
        return render(request, 'my_public_diaries.html', context)


@login_required
def all_entries(request, page_number=1):
    if request.method == "GET":
        PageView.objects.get_or_create(url='entries')
        entrance_url('entries')
        search_query = request.GET.get('s', '')
        rec_user = Entry.objects.filter(
            Q(user_id=request.user.id) & (Q(header__icontains=search_query) | Q(text__icontains=search_query))
        )
        quantity_entries = rec_user.count()

        current_page = Paginator(rec_user, 25)

        profile_image = get_object_or_404(Profile, user_id=request.user.id)
        context = {
            'quantity_entries': quantity_entries,
            'keyword_search': search_query,
            'profile': profile_image
        }
        if search_query:
            context['entries'] = rec_user
        else:
            context['entries'] = current_page.page(page_number)

        return render(request, 'all_entries.html', context)


@login_required
def detail_entry(request, entry_id):
    try:
        entry = Entry.objects.get(id=entry_id, user=request.user)
    except Entry.DoesNotExist:
        messages.error(request, f'Entry {entry_id} does not exist!')
        return redirect('all_entries')

    context = {'entry': entry, 'profile': Profile.objects.filter(user=request.user).first()}
    return render(request, 'detail_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = get_object_or_404(Entry, id=entry_id)
    if request.method == "GET":
        if entry.user_id != request.user.id:
            context = {'form': AuthenticationForm()}
            return render(request, 'login.html', context)

        entry.delete_image = False
        profile_image = Profile.objects.filter(user_id=request.user.id).first()
        context = {'form': EntryForm(model_to_dict(entry)), 'entry': entry, 'profile': profile_image}
        return render(request, 'edit_entry.html', context)
    elif request.method == "POST":
        form = EntryForm(request.POST, request.FILES)
        if form.is_valid():
            if request.is_ajax():
                entry.header = request.POST.get('header')
                entry.text = request.POST.get('text')
                entry.voice_record = request.FILES.get('audio_data')
                entry.image = request.FILES.get('image')
                entry.delete_image = json.loads(request.POST.get('delete_image', 'false').lower())
            else:
                data = form.cleaned_data
                entry.header = data['header']
                entry.text = data['text']
                entry.image = request.FILES.get('image', entry.image)
                entry.delete_image = data.get('delete_image', False)
                if entry.delete_image:
                    entry.image.delete()

            entry.check_edit = True
            entry.save()
            messages.success(request, 'The entry details updated.')
            success = True
            if request.is_ajax():
                return JsonResponse({'success': success})

            return redirect('detail_entry', entry_id)

        success = False
        if request.is_ajax():
            return JsonResponse({'success': success})

        return render(request, 'edit_entry.html', {'form': form, 'entry': entry})


def delete_voice_record(entry_id):
    """Delete voice record"""
    entry = get_object_or_404(Entry, id=entry_id)
    entry.voice_record.delete()
    return {'success': True}


@login_required
def delete_entry(request, entry_id):
    entry = Entry.objects.filter(id=entry_id, user_id=request.user.id).first()
    if not entry:
        context = {'form': AuthenticationForm()}
        return render(request, 'login.html', context)
    if request.method == 'POST':
        entry.delete()
        messages.success(request, 'The entry deleted.')
        return redirect('all_entries')


@login_required
def open_image(request, entry_id):
    entry = Entry.objects.filter(id=entry_id, user=request.user).first()
    if not entry:
        return render(request, 'login.html', {'form': AuthenticationForm()})
    return render(request, 'open_image.html', {'entry': entry})

import requests
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Entry

@require_http_methods(["POST"])
def send_entry(request, entry_id):
    entry = get_object_or_404(Entry, id=entry_id, user=request.user)
    user = request.user

    subject = 'Sending your entry from Diary'
    from_email = 'antonkomp1@gmail.com'
    to = user.email

    html_content = render_to_string('email/send_entry.html', {'user': user, 'form': entry})
    print(html_content)

    url = 'https://www.googleapis.com/gmail/v1/users/me/messages/send?key=' + 'AIzaSyBCJMCzBf4IwmwyyMBDd3yQ_CX3cN7lfSs' # settings.GOOGLE_API_KEY

    message = {'raw': base64.urlsafe_b64encode(html_content.encode('utf-8')).decode('utf-8')}

    body = {'raw': base64.urlsafe_b64encode(html_content.encode('utf-8')).decode('utf-8')}
    print(body)

    headers = {
        'Authorization': 'Bearer ' + 'AIzaSyBCJMCzBf4IwmwyyMBDd3yQ_CX3cN7lfSs', # settings.GOOGLE_API_KEY,
        'Content-Type': 'application/json'
    }

    response = requests.post(url, headers=headers, json=body)
    print(response.text)

    if response.status_code == 200:
        messages.success(request, 'The entry was successfully sent to email!')
    else:
        messages.error(request, 'An error occurred while sending the email.')

src/records/templates/add_entry.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Add entry {% endblock %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'css/entries/add_entry.css' %}" />
    <link rel="stylesheet" href="{% static 'css/voice_record.css' %}" />
    <script type="text/javascript" src="{% static 'js/recorder.js' %}"></script>
{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Add entry</h3>
        {{ form|crispy }}
        <input type="button" class="but_voice_record" value="Voice record">
        <div class="voice_recording" id="id_voice_record" style="display:none">
            <div id="controls">
             <button id="recordButton" type='button'>Record</button>
             <button id="pauseButton" disabled type='button'>Pause</button>
             <button id="stopButton" disabled>Stop</button>
            </div>
            <ol id="recordingsList"></ol>
        </div>
        <button class="save" id="save_btn" type="submit">Save</button>
        <script type="text/javascript" src="{% static 'js/voice_record.js' %}"></script>
    </form>
    <hr>
    <a class="all_entries" href="{% url 'all_entries' %}"> My entries </a><br><br>
    <script>
        $(".but_voice_record").click(function(){
            $(".voice_recording").toggle();
        });
        $("input[type=checkbox]").keydown(function(event){
            if(event.keyCode == 13){
              event.preventDefault();
                return false;
            }
        });
        $('#id_header').keyup(function () {
            var header_value = document.getElementById('id_header').value;
            if (/^ *$/.test(header_value)) {
                $('#headerError').remove();
                $('#id_header').removeClass('is-valid').addClass('is-invalid');
                $('#id_header').after('<div class="invalid-feedback" id="headerError">The header is empty!</div>')
                $('#id_header').css({"border-color": "red", "background": "#FDF5F5"});
                $('#save_btn').attr("disabled", true);
                $('#save_btn').css({"background": "#9c9c9c"});
            }
            else {
                $('#id_header').removeClass('is-invalid').addClass('is-valid');
                $('#headerError').remove();
                $('#id_header').css({"border-color": "black", "background": "#eceff3"});
                $('#save_btn').removeAttr("disabled");
                $('#save_btn').css({"background": "#1a73e8"});
            }
        });
        $(".clearablefileinput").click(function(){
            setTimeout(loadAfterTime, 1500);
        });
        function loadAfterTime() {
            $("#div_id_delete_image").show()
        }
    </script>
{% endblock %}

src/records/templates/add_record.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Add entry {% endblock %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'css/records/add_record.css' %}" />
    <link rel="stylesheet" href="{% static 'css/voice_record.css' %}" />
    <script type="text/javascript" src="{% static 'js/recorder.js' %}"></script>
{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Add entry</h3>
        {{ form|crispy }}
        <input type="button" class="but_voice_record" value="Voice record">
        <div class="voice_recording" id="id_voice_record" style="display:none">
            <div id="controls">
             <button id="recordButton" type='button'>Record</button>
             <button id="pauseButton" disabled type='button'>Pause</button>
             <button id="stopButton" disabled>Stop</button>
            </div>
            <ol id="recordingsList"></ol>
        </div>
        <button class="save" id="save_btn" type="submit">Save</button>
        <script type="text/javascript" src="{% static 'js/voice_record.js' %}"></script>
    </form>
    <hr>
    <a class="all_records" href="{% url 'all_records' %}"> My entries </a><br><br>
    <script>
        $(".but_voice_record").click(function(){
            $(".voice_recording").toggle();
        });
        $("input[type=checkbox]").keydown(function(event){
            if(event.keyCode == 13){
              event.preventDefault();
                return false;
            }
        });
        $('#id_header').keyup(function () {
            var header_value = document.getElementById('id_header').value;
            if (/^ *$/.test(header_value)) {
                $('#headerError').remove();
                $('#id_header').removeClass('is-valid').addClass('is-invalid');
                $('#id_header').after('<div class="invalid-feedback" id="headerError">The header is empty!</div>')
                $('#id_header').css({"border-color": "red", "background": "#FDF5F5"});
                $('#save_btn').attr("disabled", true);
                $('#save_btn').css({"background": "#9c9c9c"});
            }
            else {
                $('#id_header').removeClass('is-invalid').addClass('is-valid');
                $('#headerError').remove();
                $('#id_header').css({"border-color": "black", "background": "#eceff3"});
                $('#save_btn').removeAttr("disabled");
                $('#save_btn').css({"background": "#1a73e8"});
            }
        });
        $(".clearablefileinput").click(function(){
            setTimeout(loadAfterTime, 1500);
        });
        function loadAfterTime() {
            $("#div_id_delete_image").show()
        }
    </script>
{% endblock %}

src/records/templates/all_public_diaries.html
{% extends "base.html" %}
{% block title %} My entries {% endblock %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'css/entries/all_entries.css' %}" />
{% endblock %}
{% block content %}
    {% for message in messages %}
    <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-info{% endif %}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    <h3>All public diaries</h3>

{% endblock %}

src/records/templates/create_new_diary.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Create new diary {% endblock %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'css/entries/all_entries.css' %}" />
{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Create new diary</h3>
        {{ form|crispy }}
        <button class="create" id="create_btn" type="submit">Create</button>
    </form>
    <hr>
    <a class="my_public_diaries" href="{% url 'my_public_diaries' %}"> My public diaries </a><br><br>
{% endblock %}

src/records/templates/edit_entry.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Edit entry {% endblock %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'css/entries/edit_entry.css' %}" />
    <link rel="stylesheet" href="{% static 'css/voice_record.css' %}" />
    <script type="text/javascript" src="{% static 'js/recorder.js' %}"></script>
{% endblock %}
{% block content %}
    <h3>Edit entry</h3>
    <form action='{% url "edit_entry" entry_id=entry.id %}' method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        {% if entry.image %}
            <p id="loaded_image">Loaded: {{ entry.image }} </p>
        {% endif %}
        {% if entry.voice_record %}
            <div class="voice_record">
                <audio
                    controls
                    src="{{ entry.voice_record.url }}">
                        Your browser does not support the
                        <code>audio</code> element.
                </audio>
                <button id="del_exist_voice" type="button"><i class='fa fa-trash'></i></button>
            </div>
        {% else %}
            <input type="button" class="but_voice_record" value="Voice record">
        {% endif %}
        <div class="voice_recording" id="id_voice_record" style="display:none">
            <div id="controls">
             <button id="recordButton" type='button'>Record</button>
             <button id="pauseButton" disabled type='button'>Pause</button>
             <button id="stopButton" disabled>Stop</button>
            </div>
            <ol id="recordingsList"></ol>
        </div>
        <button class="save" id="save_btn" type="submit">Save</button>
        <script type="text/javascript" src="{% static 'js/voice_record_edit.js' %}"></script>
    </form>
    <hr>
    <a class="all_entries" href="{% url 'all_entries' %}"> My entries </a><br><br>
    <script>
        var id  = {{ entry.id }}
        $(".but_voice_record").click(function(){
            $(".voice_recording").toggle();
        });
        if ($("#loaded_image").length > 0){
           $("#div_id_delete_image").show()
        }
        else {
           $("#div_id_delete_image").hide()
        }
        $(".clearablefileinput").click(function(){
            setTimeout(loadAfterTime, 1500);
        });
        function loadAfterTime() {
            $("#div_id_delete_image").show()
        }
        $("#id_delete_image,#id_header").keydown(function(event){
            if(event.keyCode == 13){
              event.preventDefault();
                return false;
            }
        });
        $('#id_header').keyup(function () {
            var header_value = document.getElementById('id_header').value;
            if (/^ *$/.test(header_value)) {
                $('#headerError').remove();
                $('#id_header').removeClass('is-valid').addClass('is-invalid');
                $('#id_header').after('<div class="invalid-feedback" id="headerError">The header is empty!</div>')
                $('#id_header').css({"border-color": "red", "background": "#FDF5F5"});
                $('#save_btn').attr("disabled", true);
                $('#save_btn').css({"background": "#9c9c9c"});
            }
            else {
                $('#id_header').removeClass('is-invalid').addClass('is-valid');
                $('#headerError').remove();
                $('#id_header').css({"border-color": "black", "background": "#eceff3"});
                $('#save_btn').removeAttr("disabled");
                $('#save_btn').css({"background": "#1a73e8"});
            }
        });
        $('#del_exist_voice').click(function () {
            $(".voice_record").remove();
            $("#id_voice_record").css({"display": "block", "margin-top": "1em"});
            $.ajax({
                url: "{% url 'delete_voice_record' entry_id=entry.id %}",
                success: function (data) {
                    console.log('response' + JSON.stringify(data));
                },
                error: function (data) {
                    console.log('response' + JSON.stringify(data));
                }
            });
            return false;
        });
    </script>
{% endblock %}

src/records/templates/edit_record.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Edit entry {% endblock %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'css/records/edit_record.css' %}" />
    <link rel="stylesheet" href="{% static 'css/voice_record.css' %}" />
    <script type="text/javascript" src="{% static 'js/recorder.js' %}"></script>
{% endblock %}
{% block content %}
    <h3>Edit entry</h3>
    <form action='{% url "edit_record" record_id=record.id %}' method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        {% if record.image %}
            <p id="loaded_image">Loaded: {{ record.image }} </p>
        {% endif %}
        {% if record.voice_record %}
            <div class="voice_record">
                <audio
                    controls
                    src="{{ record.voice_record.url }}">
                        Your browser does not support the
                        <code>audio</code> element.
                </audio>
                <button id="del_exist_voice" type="button"><i class='fa fa-trash'></i></button>
            </div>
        {% else %}
            <input type="button" class="but_voice_record" value="Voice record">
        {% endif %}
        <div class="voice_recording" id="id_voice_record" style="display:none">
            <div id="controls">
             <button id="recordButton" type='button'>Record</button>
             <button id="pauseButton" disabled type='button'>Pause</button>
             <button id="stopButton" disabled>Stop</button>
            </div>
            <ol id="recordingsList"></ol>
        </div>
        <button class="save" id="save_btn" type="submit">Save</button>
        <script type="text/javascript" src="{% static 'js/voice_record_edit.js' %}"></script>
    </form>
    <hr>
    <a class="all_records" href="{% url 'all_records' %}"> My entries </a><br><br>
    <script>
        var id  = {{ record.id }}
        $(".but_voice_record").click(function(){
            $(".voice_recording").toggle();
        });
        if ($("#loaded_image").length > 0){
           $("#div_id_delete_image").show()
        }
        else {
           $("#div_id_delete_image").hide()
        }
        $(".clearablefileinput").click(function(){
            setTimeout(loadAfterTime, 1500);
        });
        function loadAfterTime() {
            $("#div_id_delete_image").show()
        }
        $("#id_delete_image,#id_header").keydown(function(event){
            if(event.keyCode == 13){
              event.preventDefault();
                return false;
            }
        });
        $('#id_header').keyup(function () {
            var header_value = document.getElementById('id_header').value;
            if (/^ *$/.test(header_value)) {
                $('#headerError').remove();
                $('#id_header').removeClass('is-valid').addClass('is-invalid');
                $('#id_header').after('<div class="invalid-feedback" id="headerError">The header is empty!</div>')
                $('#id_header').css({"border-color": "red", "background": "#FDF5F5"});
                $('#save_btn').attr("disabled", true);
                $('#save_btn').css({"background": "#9c9c9c"});
            }
            else {
                $('#id_header').removeClass('is-invalid').addClass('is-valid');
                $('#headerError').remove();
                $('#id_header').css({"border-color": "black", "background": "#eceff3"});
                $('#save_btn').removeAttr("disabled");
                $('#save_btn').css({"background": "#1a73e8"});
            }
        });
        $('#del_exist_voice').click(function () {
            $(".voice_record").remove();
            $("#id_voice_record").css({"display": "block", "margin-top": "1em"});
            $.ajax({
                url: "{% url 'delete_voice_record' record_id=record.id %}",
                success: function (data) {
                    console.log('response' + JSON.stringify(data));
                },
                error: function (data) {
                    console.log('response' + JSON.stringify(data));
                }
            });
            return false;
        });
    </script>
{% endblock %}

src/records/templates/my_public_diaries.html
{% extends "base.html" %}
{% block title %} My entries {% endblock %}
{% load static %}
{% block static %}
    <link rel="stylesheet" href="{% static 'css/entries/all_entries.css' %}" />
    <link rel="stylesheet" href="{% static 'css/entries/my_public_diaries.css' %}" />
{% endblock %}
{% block content %}
    {% for message in messages %}
    <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-info{% endif %}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    <h3>My public diaries</h3>
    <a class="create_new_diary" href="{% url 'create_new_diary' %}"> Create new diary </a><br>

     <!-- new table -->
        <div class="content_entries">
        <div class="tableBlock">
            <div style="display: flex; box-sizing: border-box;">
                <div class="head_col">Name</div>
                <div class="head_col">Header</div>
                <div class="head_col head_right">Action</div>
            </div>
            <hr class="hr_head">
        {% for diary in diaries %}
            <div class="tableBlock__row">
                <div class="entr_col">
                    <a href=""><label class="fa fa-calendar-check-o"></label>
                        {{ diary.name }}
                    </a>
                </div>
            </div>
        {% endfor %}
        </div>
        </div>

{% endblock %}

src/records/templates/open_image.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Original image</title>
    <style>
       body {
        background: #2C2928; /* Цвет фона */
        color: DimGrey; /* Цвет текста */
       }
  </style>
</head>
<body>
    <p style="text-align: center;"><img src="{{ entry.image.url }}" alt="picture"></p>
</body>
</html>